#!/bin/sh
#
#  octopus postinst
#
#  Shamelessly ripped off of Marcelo Magallon's script
#     by Brent Fulgham <bfulgham@debian.org>
#
#
# Ripped off blackbox's postinst, by Matt Hope <dopey@debian.org>
#
set -e

WMentry="/usr/bin/octopus"

add_wm_entry ()
{
	update-alternatives --install /usr/bin/x-window-manager x-window-manager $WMentry 50
	#--slave /usr/share/man/man1/x-window-manager.1.gz x-window-manager.1.gz /usr/share/man/man1/octopus.1.gz
}

case "$1" in
    configure)
        add_wm_entry
    ;;

    abort-*)
        # how did we get here?  Force a non-zero exit code
        exit 1
    ;;

    *)
    ;;
esac

# End automatically added section

