#!/bin/sh
set -e

Octopus_entry="/usr/bin/octopus"

case "$1" in
    remove)

	if [ -x /usr/sbin/update-alternatives ]; then
	    update-alternatives --remove x-window-manager $Octopus_entry
	fi

        if [ -x /usr/sbin/register-window-manager ] ; then
	    register-window-manager --remove $Octopus_entry
        fi

        ;;
    *)
        ;;
esac
